# IDs used by the grass wind animation in gbuffers_terrain.vsh and shadow.vsh.
block.101 = minecraft:grass minecraft:fern
block.102 = minecraft:tall_grass:half=lower minecraft:large_fern:half=lower
block.103 = minecraft:tall_grass:half=upper minecraft:large_fern:half=upper
block.104 = minecraft:dead_bush
