size.buffer.colortex1=0.5 0.5
size.buffer.colortex2=0.25 0.25
blend.gbuffers_water.colortex4=off
blend.gbuffers_hand.colortex3=off
blend.gbuffers_hand.colortex4=off
blend.gbuffers_hand_water.colortex3=off
blend.gbuffers_hand_water.colortex4=off
